## `softlink/verify` — the compile-time C header signature verification
## codegen shared by `dynlib` and `verifyProcs`: `genVerifyBlock` (the
## three-tier `_Static_assert`/`__builtin_types_compatible_p`/`_Generic`
## fallback chain) and RFC-0001 §4 B.2's probe-mode machinery
## (`-d:softlinkProbeOnly`/`-d:softlinkProbeExistence`) that gates which
## procs in a block get verification apparatus emitted at all. Extracted
## from `src/softlink.nim` (code-review finding #13): `genVerifyBlock` and
## its helpers take their inputs as explicit parameters
## (`seq[SoftlinkProc]`, a tag string, a bool) and read only module-level
## `{.strdefine.}`/`{.booldefine.}` consts — none of it closes over any
## `dynlib`/`verifyProcs` macro local.

import std/[macros, strutils, sets]
import ./procinfo

func toIncludeDirective*(header: string): string =
  ## Convert a header path to a C #include directive.
  ## Supports angle-bracket syntax: ``"<mbedtls/ssl.h>"`` → ``#include <mbedtls/ssl.h>``
  ## and quoted syntax: ``"mbedtls/ssl.h"`` → ``#include "mbedtls/ssl.h"``
  if header.len >= 2 and header[0] == '<' and header[^1] == '>':
    "#include " & header & "\n"
  else:
    "#include \"" & header & "\"\n"

func emitPrototypeDecl(prototype: string, verifyWhen: string): string =
  ## Render RFC-0001 §3 A.1's vendored-prototype file-scope `extern`
  ## declaration for one proc's `{.prototype: "<C prototype>".}`. Emitted
  ## into the verify TU after the block's `#include`s (so named types
  ## resolve) and before the verify proc body — the same `includeCode`
  ## blob `genVerifyBlock` already builds for headers, just appended.
  ##
  ## Wrapped in `extern "C" { ... }` under the C++ backend: C11 6.7p4 makes
  ## an incompatible same-scope redeclaration a mandatory diagnostic, but
  ## without C linkage a drifted upstream declaration is a legal *overload*
  ## in C++ — overload resolution would quietly pick the header's
  ## declaration and the drift tripwire (benefit 3 of A.1) would never
  ## fire. The `#if defined(__cplusplus)` guard is inert (but present) in
  ## the C-backend output too — the emitted text is backend-agnostic; only
  ## the C preprocessor decides which branch survives.
  ##
  ## When `{.verifyWhen.}` is also present, the declaration itself is gated
  ## by the same `#if (EXPR)` as its assert (A.1: "composes... both the
  ## emitted declaration and its assert are gated by the #if") — needed
  ## when the vendored prototype references types absent from old headers.
  var decl = "#if defined(__cplusplus)\nextern \"C\" {\n#endif\n" &
    "extern " & prototype & ";\n" &
    "#if defined(__cplusplus)\n}\n#endif\n"
  if verifyWhen.len > 0:
    decl = "#if (" & verifyWhen & ") /* softlink verifyWhen: prototype decl */\n" &
      decl & "#endif /* softlink verifyWhen */\n"
  decl

const softlinkProbeOnly {.strdefine.} = ""
  ## RFC-0001 §4 B.2: with `-d:softlinkProbeOnly=<CName>`, `genVerifyBlock`
  ## suppresses the ENTIRE verification apparatus (the call-based
  ## `_Static_assert` chain AND any `{.prototype.}` extern declaration —
  ## see `emitPrototypeDecl`) for every proc EXCEPT the one whose C name
  ## equals `<CName>`. Block-level `#include`s are STILL emitted regardless
  ## — the harvester's baseline probe exists precisely to detect broken
  ## corpus headers, so the includes must run even when nothing else does.
  ## The sentinel value `"-"` suppresses verification for every proc (the
  ## harvester's baseline mode: "do the headers even compile").
  ##
  ## RFC §4 B.2's optional fast-path (slice B7): `<CName>` may instead be a
  ## comma-separated LIST of C names (`<CName1,CName2,...>`) — the
  ## suppression rule generalizes to "suppress every proc whose C name is
  ## NOT a member of the list." A singleton list behaves identically to the
  ## pre-B7 single-name form (backward compatible by construction — see
  ## `isSuppressed`). This supersedes the B2-era comment that used to live
  ## here, which said a comma-containing value "degrades to suppress
  ## everything": that was true only because no list parsing existed yet.
  ## `parseProbeOnlyList` (below) now does the real parsing:
  ## - list elements are used VERBATIM — never trimmed. Defines are
  ##   machine-generated by the harvester's bisection, never hand-typed, so
  ##   a legitimate list is always a clean comma-join with no incidental
  ##   whitespace; a whitespace-padded element (e.g. from hand-editing)
  ##   simply never equals any real C name, so it fails CLOSED (that
  ##   element selects nothing) rather than requiring a second validation
  ##   pass to detect it.
  ## - an EMPTY element (from a leading/trailing/doubled comma, e.g.
  ##   `a,,b`) is always a macro-expansion-time error naming the malformed
  ##   define — same no-silent-degradation principle as everywhere else in
  ##   this file: a malformed list must never silently partial-match.
  ## Harvest-only, like `softlinkDumpProbes`: a dedicated single-shot
  ## invocation, not something left set in ordinary dev/CI builds. Default
  ## `""` (unset) is a no-op — every existing `dynlib`/`verifyProcs` block
  ## compiles byte-identically, because every check below short-circuits on
  ## `softlinkProbeOnly.len == 0` before touching emission at all.

const softlinkProbeExistence {.booldefine.} = false
  ## RFC-0001 §4 B.2: with `-d:softlinkProbeExistence` (meaningful only
  ## together with `-d:softlinkProbeOnly=<CName>` naming a real symbol),
  ## the probed symbol's verification is replaced by a bare
  ## declaration-existence reference — `__typeof__(&sym)` / `decltype(&sym)`
  ## through the SAME three-tier compiler gating the call-based assert
  ## uses — instead of the full call-based assert chain: it compiles iff
  ## the corpus headers declare the symbol at ANY signature, independent of
  ## what that signature is. The probed symbol's own `{.prototype.}` extern
  ## declaration (if any) is ALSO suppressed in this mode: emitting it would
  ## let `__typeof__`/`decltype` resolve against the *vendored* prototype
  ## even when the corpus header doesn't declare the symbol at all, making
  ## `absent` unclassifiable for header+prototype procs (the RFC's
  ## classification table depends on the existence probe reflecting the
  ## HEADER alone). A `{.verifyWhen.}` gate on the probed proc wraps the
  ## existence reference exactly as it would wrap the assert. Set without
  ## `softlinkProbeOnly` naming a real symbol (unset, or the `"-"`
  ## all-suppress sentinel) is a meaningless probe configuration — see the
  ## macro error raised in `genVerifyBlock` below — rather than silently
  ## compiling as some other mode. RFC §4 B.2 slice B7: a MULTI-symbol
  ## `softlinkProbeOnly` list combined with this define is ALSO a macro
  ## error (see `genVerifyBlock`) — existence is a per-singleton stage of
  ## the standard three-probe pipeline; a group existence probe is
  ## meaningless (the fast path's bisection only ever runs multi-symbol
  ## compiles in verify mode).

proc parseProbeOnlyList(raw: string, posNode: NimNode): seq[string] =
  ## RFC-0001 §4 B.2, slice B7: parses a non-empty, non-`"-"`
  ## `softlinkProbeOnly` value into its list of target C names. Callers
  ## only invoke this once `raw` is known to be neither `""` (unset) nor
  ## `"-"` (the all-suppress sentinel) — both are handled by their own
  ## checks before this is ever reached.
  ##
  ## A value with no comma is the pre-B7 singleton form, returned as a
  ## one-element list (so every downstream check — `isSuppressed`,
  ## `isProbedExistence` — written in terms of list membership is
  ## byte-for-byte backward compatible with the pre-list-support behavior).
  ##
  ## A comma-containing value splits on `,`, verbatim, no trimming (see the
  ## `softlinkProbeOnly` const's doc comment for why untrimmed is the
  ## chosen — not merely default — behavior). Any resulting EMPTY element
  ## (a leading, trailing, or doubled comma) is a macro-expansion-time
  ## error: the harvester's own bisection always emits a clean comma-join,
  ## so an empty element only ever means a hand-malformed define, and per
  ## this project's no-silent-degradation principle (identical in spirit
  ## to B2's original guidance for this exact spot) that must be a loud
  ## error, never a silent partial match.
  if "," notin raw:
    return @[raw]
  let parts = raw.split(",")
  for i, part in parts:
    if part.len == 0:
      error("softlink: malformed -d:softlinkProbeOnly=\"" & raw & "\" — " &
        "element " & $(i + 1) & " of " & $parts.len & " is empty (from a " &
        "leading, trailing, or doubled comma). RFC-0001 §4 B.2's fast-path " &
        "bisection (slice B7) always emits a clean comma-joined list of C " &
        "names with no empty elements — this is a malformed define, and " &
        "per this project's no-silent-degradation principle it is a " &
        "compile-time error rather than a silent partial match.", posNode)
  parts

proc genVerifyBlock*(allProcs: seq[SoftlinkProc], tag: string,
                     hasManifestAttached: bool = false): seq[NimNode] =
  ## Generate the compile-time C header signature verification nodes
  ## (include section + a file-local _Static_assert proc). Shared by
  ## `dynlib` and `verifyProcs`.
  ##
  ## `hasManifestAttached` (RFC-0001 §B.5 check 9, slice B6a): true iff
  ## `applyCompatManifest` attached a (non-ABI-ignored) compat manifest to
  ## this block. When true, every proc's graceful `#else` fallback (the
  ## no-verification tier — see the "Fallback: graceful degradation"
  ## comment below) gains a `#pragma message` noting that this specific
  ## compile did NOT re-verify the manifest's facts — a green manifest and
  ## a degraded verification tier must never blur together into one
  ## "everything is fine" signal. `false` (the default) reproduces today's
  ## emission byte-for-byte.
  # {.noverify.} procs are excluded entirely — no _Static_assert AND no
  # #include of their header. A noverify symbol typically doesn't exist in
  # the installed headers (that's why verification is skipped), and its call
  # expression would be an implicit-declaration error in C. See #14/Defect B:
  # {.optional.} alone is runtime-optional but still compile-time verified.
  #
  # A {.prototype.} proc (RFC-0001 §3 A.1) verifies even with no {.header.}:
  # the vendored prototype is emitted as a file-scope `extern` declaration
  # (see `emitPrototypeDecl`) below the block's #includes, giving the
  # subsequent call-based _Static_assert something real to check against —
  # no implicit-declaration error, because the symbol is now declared.
  # A proc carrying BOTH {.header.} and {.prototype.} (cross-checking) gets
  # BOTH declarations; if they disagree, the C compiler itself reports the
  # conflict (opportunistic conflict checking, benefit 2 of A.1 — the actual
  # conflict fixture is slice A4).
  var procs: seq[SoftlinkProc]
  for p in allProcs:
    if not p.noVerify and (p.headerFile != "" or p.prototype.len > 0): procs.add(p)
  if procs.len == 0:
    return @[]

  # RFC-0001 §4 B.2: probe-mode config validation + per-proc classification.
  # `probeOnlyActive` is false whenever `softlinkProbeOnly` is at its default
  # "" value, so every predicate below is unreachable/false in the control
  # path — pre-B2 emission is untouched by construction, not merely by test.
  let probeOnlyActive = softlinkProbeOnly.len > 0
  if softlinkProbeExistence and (softlinkProbeOnly == "" or softlinkProbeOnly == "-"):
    let gotDesc =
      if softlinkProbeOnly == "": "<unset>"
      else: "'-' (the all-suppress sentinel, not a symbol name)"
    let msg = "softlink: -d:softlinkProbeExistence requires " &
      "-d:softlinkProbeOnly=<CName> naming a real probed symbol — an " &
      "existence-only probe is meaningless without exactly one target " &
      "symbol. Got softlinkProbeOnly=" & gotDesc & ". Pass the exact C " &
      "name of the symbol being probed, e.g. -d:softlinkProbeOnly=" &
      procs[0].nameStr & "."
    error(msg, allProcs[0].name)

  # RFC-0001 §4 B.2, slice B7: `probeOnlyList` is the parsed form of
  # `softlinkProbeOnly` — empty for the unset/"" and "-" (all-suppress)
  # cases (neither is ever list-membership-tested; `isSuppressed` checks
  # them directly, exactly as before B7), otherwise one or more C names.
  # `parseProbeOnlyList` itself raises a macro error (and returns its best-
  # effort partial parse, execution continuing per this file's `error()`
  # convention elsewhere) on a malformed list — see its own doc comment.
  let probeOnlyList: seq[string] =
    if softlinkProbeOnly == "" or softlinkProbeOnly == "-": @[]
    else: parseProbeOnlyList(softlinkProbeOnly, allProcs[0].name)

  if softlinkProbeExistence and probeOnlyList.len > 1:
    let msg = "softlink: -d:softlinkProbeExistence requires exactly ONE " &
      "probed symbol — got " & $probeOnlyList.len & " names in " &
      "-d:softlinkProbeOnly=" & softlinkProbeOnly & ". Existence mode is a " &
      "per-singleton stage of the standard three-probe pipeline " &
      "(RFC-0001 §4 B.2); a MULTI-symbol existence probe is meaningless. " &
      "The multi-symbol form of -d:softlinkProbeOnly is a verify-mode-only " &
      "fast-path bisection tool (RFC-0001 §4 B.2, slice B7) — drop " &
      "-d:softlinkProbeExistence to bisect, or narrow the list to exactly " &
      "one symbol to probe its existence."
    error(msg, allProcs[0].name)

  # RFC-0001 §4 B.2, coverage fix (code-review finding F9): `probeOnlyList`
  # is never checked against this block's own C names — a typo'd or stale
  # `-d:softlinkProbeOnly` value silently suppresses EVERY proc in the
  # block (the trivially-compiling verify TU gives no signal that anything
  # is wrong). `-d:softlinkProbeOnly` is deliberately GLOBAL to the whole
  # compilation, though: a module may legitimately contain MULTIPLE
  # `dynlib`/`verifyProcs` blocks, and the harvester's single invocation
  # targets exactly one of them by name — every OTHER block in that same
  # module correctly matches nothing and correctly suppresses everything.
  # A hard ERROR here would break that entirely legitimate multi-block
  # case, so this is a WARNING, not an error (unconditionally — there is
  # no existing precedent in this file for escalating a *warning* to an
  # *error* under `-d:softlinkStrictVerify`; the only escalation precedent
  # here is hint-to-warning, e.g. the {.noverify.} enumeration below, which
  # is a different severity pair and does not apply). Existence mode
  # (`softlinkProbeExistence`) gets the exact same warning, not a harder
  # one, for the identical reason: its single-symbol target not matching
  # THIS block is just as often the legitimate "targets a different block"
  # case as it is a typo.
  if probeOnlyList.len > 0:
    var blockCNames: HashSet[string]
    for p in allProcs: blockCNames.incl(p.nameStr)
    var unmatched: seq[string]
    for name in probeOnlyList:
      if name notin blockCNames:
        unmatched.add(name)
    if unmatched.len > 0:
      let msg = "softlink: -d:softlinkProbeOnly=" & softlinkProbeOnly &
        " names " & unmatched.join(", ") &
        (if unmatched.len == 1: " that matches" else: " that match") &
        " no proc in this '" & tag & "' block — if you intended to " &
        "target THIS block, this is a typo or stale name and every " &
        "proc's verification here is being silently suppressed (fatal if " &
        "so); if you intended a DIFFERENT dynlib/verifyProcs block in the " &
        "same module, this is expected and can be ignored (RFC-0001 §4 B.2)."
      warning(msg, allProcs[0].name)

  template isSuppressed(p: SoftlinkProc): bool =
    ## RFC-0001 §4 B.2 (list support: slice B7): true when this proc's
    ## entire verification apparatus (call-based assert chain AND any
    ## {.prototype.} extern decl) must be omitted this compile — probing is
    ## active and this proc is neither the "-" sentinel's "everything"
    ## target nor a member of `probeOnlyList`. A singleton list reduces to
    ## exactly the pre-B7 `p.nameStr != softlinkProbeOnly` check (byte-
    ## identical behavior — see `parseProbeOnlyList`'s doc comment).
    probeOnlyActive and (softlinkProbeOnly == "-" or p.nameStr notin probeOnlyList)

  template isProbedExistence(p: SoftlinkProc): bool =
    ## RFC-0001 §4 B.2: true when this proc IS the probed symbol AND
    ## existence-only mode was requested — its call-based assert is
    ## replaced by a bare declaration-existence reference, and its own
    ## {.prototype.} extern decl (if any) is ALSO suppressed (see the
    ## `softlinkProbeExistence` const doc comment for why that matters).
    ## `probeOnlyList.len == 1` is redundant with the macro error raised
    ## above whenever `softlinkProbeExistence` and a multi-symbol list
    ## coexist, but guards this predicate against acting on a partially-
    ## parsed multi-symbol list while that error is still propagating.
    probeOnlyActive and softlinkProbeExistence and probeOnlyList.len == 1 and
      p.nameStr == probeOnlyList[0]

  var nodes: seq[NimNode] = @[]
  # Compile-time header verification. Compares each symbol's type from
  # the C header against Nim's generated function pointer type.
  # Three-tier fallback for maximum compiler compatibility:
  #   1. C23 typeof (standard)
  #   2. __typeof__ (GCC/Clang extension, also MSVC 2022+)
  #   3. C++ decltype + std::is_same (for --backend:cpp)
  # No linking required — pure compile-time check.
  block:
    var headers: HashSet[string]
    var includeCode = ""
    for p in procs:
      # `procs` now includes prototype-only entries (no {.header.}) per
      # RFC-0001 §3 A.1 slice A2 — the empty-headerFile guard here is load-
      # bearing, not defensive dead code: without it a prototype-only proc
      # would emit `#include ""`, a compile error.
      if p.headerFile != "" and p.headerFile notin headers:
        headers.incl(p.headerFile)
        includeCode.add(toIncludeDirective(p.headerFile))

    # Vendored-prototype extern declarations (RFC-0001 §3 A.1), emitted
    # after all of this block's #includes so any named types the prototype
    # references resolve, and before the type_traits/verify-proc code below.
    # A proc with both {.header.} and {.prototype.} gets both declarations —
    # cross-checking (A.1 benefit 2); the C compiler itself flags disagreement.
    #
    # RFC-0001 §4 B.2: a suppressed proc's decl is omitted entirely — a
    # suppressed proc's vendored prototype conflicting with a corpus header
    # would fail the whole TU and poison the probe of the TARGET symbol. The
    # probed symbol's OWN decl is also omitted under existence mode — see
    # `isProbedExistence`'s doc comment for why that's load-bearing, not
    # merely symmetric.
    for p in procs:
      if p.prototype.len > 0 and not isSuppressed(p) and not isProbedExistence(p):
        includeCode.add(emitPrototypeDecl(p.prototype, p.verifyWhen))

    # Emit #include directives + C++ type_traits if needed
    nodes.add(newNimNode(nnkPragma).add(
      newNimNode(nnkExprColonExpr).add(
        ident("emit"),
        newStrLitNode("/*INCLUDESECTION*/\n" & includeCode &
          "#if defined(__cplusplus)\n" &
          "#include <type_traits>\n" &
          "#ifndef SOFTLINK_STRIP_PTR_CONST_DEFINED\n" &
          "#define SOFTLINK_STRIP_PTR_CONST_DEFINED 1\n" &
          "template<typename T> struct softlink_strip_ptr_const { typedef T type; };\n" &
          "template<typename T> struct softlink_strip_ptr_const<const T*> { typedef T* type; };\n" &
          "#endif\n" &
          "#endif\n")
      )
    ))

    # Emit per-proc verification inside a dummy proc to ensure the
    # assertions appear after function pointer var declarations in
    # the generated C code (file-scope emit can't reference these vars).
    # NOTE: {.used.} alone is not sufficient — Nim's dead code elimination
    # drops the proc entirely. {.exportc.} forces Nim to emit the proc.
    # {.codegenDecl: "static ...".} makes it file-local in C — no linker
    # collisions, no binary bloat. _Static_assert is evaluated at C
    # compilation time (during gcc -c), before LTO runs at link time —
    # the assertions cannot be eliminated by link-time optimization.
    var verifyBody = newStmtList()
    for p in procs:
      # RFC-0001 §4 B.2: a suppressed proc gets NO verification apparatus at
      # all this compile — not even the dummy param vars, which exist only
      # to feed the call-based assert chain this proc isn't getting.
      if isSuppressed(p):
        continue

      if isProbedExistence(p):
        # RFC-0001 §4 B.2: existence-only mode for the probed symbol — a
        # bare declaration-existence reference through the SAME three-tier
        # compiler gating the call-based assert uses, instead of the call-
        # based assert itself. No dummy param vars are needed (nothing is
        # called); the reference must compile iff the symbol is declared,
        # with NO dependence on its signature — `sizeof(__typeof__(&sym))` /
        # `sizeof(decltype(&sym))` (the C++ tier) fit exactly: they name the
        # symbol (so an undeclared symbol is a hard compile error) but
        # `sizeof` never evaluates its operand, so any real signature works.
        var existArray = newNimNode(nnkBracket)
        if p.verifyWhen.len > 0:
          existArray.add(newStrLitNode(
            "\n#if (" & p.verifyWhen & ") /* softlink verifyWhen */"))
        existArray.add(newStrLitNode(
          "\n#if defined(__cplusplus)\n(void)sizeof(decltype(&" &
          p.nameStr & "));\n" &
          "#elif defined(__GNUC__)\n(void)sizeof(__typeof__(&" &
          p.nameStr & "));\n" &
          "#elif defined(_MSC_VER) && defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L\n" &
          "(void)sizeof(__typeof__(&" & p.nameStr & "));\n"))
        when defined(softlinkStrictVerify):
          existArray.add(newStrLitNode(
            "#else\n#error \"softlink: existence probe unavailable here " &
            "(need C++, GCC/Clang, or MSVC /std:clatest); remove " &
            "-d:softlinkStrictVerify to skip\"\n#endif\n"))
        else:
          existArray.add(newStrLitNode(
            "#else\n/* softlink: existence probe skipped — unsupported " &
            "compiler/mode */\n#endif\n"))
        if p.verifyWhen.len > 0:
          existArray.add(newStrLitNode("#endif /* softlink verifyWhen */\n"))
        verifyBody.add(newNimNode(nnkPragma).add(
          newNimNode(nnkExprColonExpr).add(ident("emit"), existArray)
        ))
        continue

      # Generate dummy variables for each param — Nim emits typed C locals.
      # These are passed to the C function call, enabling const-tolerant
      # param checking (int* implicitly converts to const int* in C).
      var dummyVars: seq[NimNode]
      for i in 1 ..< p.formalParams.len:
        let identDefs = p.formalParams[i]
        let paramType = identDefs[^2]  # type is second-to-last
        for j in 0 ..< identDefs.len - 2:  # one var per name
          let dummyName = genSym(nskVar, "softlinkP")
          var varSection = newNimNode(nnkVarSection).add(
            newNimNode(nnkIdentDefs).add(dummyName, paramType.copy(), newEmptyNode())
          )
          # Add {.used, noinit.} pragmas
          let pragmaExpr = newNimNode(nnkPragmaExpr).add(dummyName, newNimNode(nnkPragma).add(
            ident("used"), ident("noinit")
          ))
          varSection[0][0] = pragmaExpr
          verifyBody.add(varSection)
          dummyVars.add(dummyName)

      # Build the call expression arguments for emit: "symbol(p1, p2, ...)"
      # Each dummy var is a Nim node resolved to its C name via emit array.
      let declSource =
        if p.headerFile != "": p.headerFile
        elif p.prototype.len > 0: "vendored prototype"
        else: "declaration"
      let errMsg = "softlink: " & p.nameStr & " signature mismatch vs " & declSource

      # Helper: build the call args portion of emit array
      # Result: [symName, "(", p1, ", ", p2, ", ", ..., ")"]
      proc buildCallArgs(emitArr: var NimNode, symName: string, vars: seq[NimNode]) =
        emitArr.add(newStrLitNode(symName & "("))
        for i, v in vars:
          if i > 0: emitArr.add(newStrLitNode(", "))
          emitArr.add(v)
        emitArr.add(newStrLitNode(")"))

      # Helper: add a type node to emit array, handling compound nodes
      # like nnkPtrTy that the C emitter can't render directly.
      proc addTypeToEmit(emitArr: var NimNode, typeNode: NimNode) =
        if typeNode.kind == nnkPtrTy:
          addTypeToEmit(emitArr, typeNode[0])
          emitArr.add(newStrLitNode("*"))
        else:
          emitArr.add(typeNode.copy())

      var emitArray = newNimNode(nnkBracket)

      # {.verifyWhen: "EXPR".}: gate this proc's entire verification (all
      # three compiler tiers AND the strict-mode #error fallback) on a C
      # preprocessor expression — verify on systems whose headers are new
      # enough, compile cleanly on older ones. When the condition is false,
      # skipping is legitimate, so strict mode must not fire either.
      if p.verifyWhen.len > 0:
        emitArray.add(newStrLitNode(
          "\n#if (" & p.verifyWhen & ") /* softlink verifyWhen */"))

      # --- C++ path: static_assert + strip_ptr_const + decltype ---
      # strip_ptr_const removes const from pointed-to types in return values
      emitArray.add(newStrLitNode(
        "\n#if defined(__cplusplus)\nstatic_assert(\n  std::is_same<\n" &
        "    typename softlink_strip_ptr_const<decltype("))
      buildCallArgs(emitArray, p.nameStr, dummyVars)
      emitArray.add(newStrLitNode(")>::type,\n    "))
      if p.hasReturn:
        addTypeToEmit(emitArray, p.formalParams[0])
      else:
        emitArray.add(newStrLitNode("void"))
      emitArray.add(newStrLitNode(
        ">::value,\n  \"" & errMsg & "\"\n);\n"))

      # --- GCC/Clang path: __builtin_types_compatible_p + __typeof__ ---
      # For pointer returns, dereference both sides so __builtin_types_compatible_p
      # strips top-level const (e.g., const unsigned char* → const unsigned char,
      # then ignoring qualifiers matches unsigned char). No linker dependency —
      # __typeof__ is purely compile-time.
      #
      # "Pointer return" here covers both `ptr T` (nnkPtrTy in Nim AST) and
      # Nim's pointer-typed aliases that aren't structurally nnkPtrTy but
      # emit as pointer types in C (`cstring` → `char*`, `cstringArray` →
      # `char**`, `pointer` → `void*`). Without the alias check, a proc
      # returning `cstring` against a C function declared `const char *`
      # (e.g., libc's `strerror`, libz3's `Z3_string`) is rejected as a
      # signature mismatch even though it's a perfectly valid binding —
      # see #11.
      let retIsPointerLike =
        p.hasReturn and (
          p.formalParams[0].kind == nnkPtrTy or
          (p.formalParams[0].kind in {nnkIdent, nnkSym} and
           $p.formalParams[0] in ["cstring", "cstringArray", "pointer"]))
      emitArray.add(newStrLitNode(
        "#elif defined(__GNUC__)\n_Static_assert(\n  __builtin_types_compatible_p(\n    __typeof__("))
      if retIsPointerLike:
        emitArray.add(newStrLitNode("*"))
      buildCallArgs(emitArray, p.nameStr, dummyVars)
      emitArray.add(newStrLitNode("),\n    "))
      if p.hasReturn:
        if retIsPointerLike:
          emitArray.add(newStrLitNode("__typeof__(*("))
          addTypeToEmit(emitArray, p.formalParams[0])
          emitArray.add(newStrLitNode(")0)"))
        else:
          addTypeToEmit(emitArray, p.formalParams[0])
      else:
        emitArray.add(newStrLitNode("void"))
      emitArray.add(newStrLitNode(
        "),\n  \"" & errMsg & "\"\n);\n"))

      # --- MSVC C path: _Generic + __typeof__ (C23 only) ---
      # MSVC only exposes _Generic and __typeof__ in C23 mode (/std:clatest), so
      # gate the whole branch on __STDC_VERSION__ >= C23. In default mode MSVC
      # doesn't even recognize _Generic — it parses as a call and errors with
      # C2059/C2275 — so without the gate every pointer-returning proc breaks the
      # build. Gated, default-mode MSVC instead falls through to the graceful
      # fallback below (no verification, but the build works). CI forces
      # /std:clatest + -d:softlinkStrictVerify so the check is genuinely exercised
      # there and can't be silently skipped (see the fallback). For pointer
      # returns the same dereference trick as the GCC path strips pointee const;
      # `retIsPointerLike` classifies cstring/cstringArray/pointer with nnkPtrTy.
      emitArray.add(newStrLitNode(
        "#elif defined(_MSC_VER) && defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L\n"))
      if retIsPointerLike:
        # Pointer return: dereference BOTH the return value and the declared
        # return type inside _Generic. _Generic applies lvalue conversion to its
        # controlling expression, which drops the pointee's top-level const —
        # so `*(__typeof__(f()))0` (type `const char`) converts to `char` and
        # matches the association `__typeof__(*(RET)0)` (`char`). This is the
        # same const-tolerant trick the GCC path (`__builtin_types_compatible_p`
        # on dereferenced operands) and the C++ path (`strip_ptr_const`) use, and
        # it reuses the identical `__typeof__(*(RET)0)` construct emitted above.
        # Before this, the branch compared `const char**` (from
        # `(__typeof__(f())*)0`) against `char**` and rejected every
        # `const char *`-returning proc — e.g. libz3's `Z3_string` (#11 on MSVC).
        emitArray.add(newStrLitNode(
          "_Static_assert(\n  _Generic(*(__typeof__("))
        buildCallArgs(emitArray, p.nameStr, dummyVars)
        emitArray.add(newStrLitNode("))0,\n    __typeof__(*("))
        addTypeToEmit(emitArray, p.formalParams[0])
        emitArray.add(newStrLitNode(
          ")0): 1, default: 0),\n  \"" & errMsg & "\"\n);\n"))
      else:
        # Non-pointer: call + _Generic __typeof__ pointer trick
        buildCallArgs(emitArray, p.nameStr, dummyVars)
        emitArray.add(newStrLitNode(";\n_Static_assert(\n  _Generic((__typeof__("))
        buildCallArgs(emitArray, p.nameStr, dummyVars)
        emitArray.add(newStrLitNode(")*)0,\n    "))
        if p.hasReturn:
          addTypeToEmit(emitArray, p.formalParams[0])
        else:
          emitArray.add(newStrLitNode("void"))
        emitArray.add(newStrLitNode(
          "*: 1, default: 0),\n  \"" & errMsg & "\"\n);\n"))

      # --- Fallback: graceful degradation ---
      # Compile-time signature verification is best-effort: it must never break an
      # otherwise-valid build. On a compiler/mode lacking the needed features —
      # notably default-mode MSVC, where _Generic/__typeof__ are unavailable — emit
      # nothing (the runtime FFI machinery is generated separately and is
      # unaffected). Opt into a hard error with `-d:softlinkStrictVerify` so a
      # silently-skipped check can't pass unnoticed; CI sets it (with the std flag
      # that opens the MSVC gate above) to guarantee the check is exercised.
      when defined(softlinkStrictVerify):
        emitArray.add(newStrLitNode(
          "#else\n#error \"softlink: signature verification unavailable here " &
          "(need C++, GCC/Clang, or MSVC /std:clatest); remove -d:softlinkStrictVerify to skip\"\n#endif\n"))
      else:
        var fallbackText =
          "#else\n/* softlink: signature verification skipped — unsupported compiler/mode */\n"
        if hasManifestAttached:
          # RFC-0001 §B.5 check 9: this build's own verification tier
          # degraded to the no-op fallback WHILE a compat manifest is
          # attached — the manifest may be green, but THIS compile
          # verified nothing, and those two facts must not blur.
          # `#pragma message` is portable across gcc/clang/MSVC.
          fallbackText.add(
            "#pragma message(\"softlink: compat manifest attached but " &
            "this compile's verification tier degraded to no-op — " &
            "manifest facts were NOT re-verified by this build\")\n")
        fallbackText.add("#endif\n")
        emitArray.add(newStrLitNode(fallbackText))

      if p.verifyWhen.len > 0:
        emitArray.add(newStrLitNode("#endif /* softlink verifyWhen */\n"))

      verifyBody.add(newNimNode(nnkPragma).add(
        newNimNode(nnkExprColonExpr).add(
          ident("emit"),
          emitArray
        )
      ))

    let verifyProcName = ident("softlinkVerify" & tag)
    var verifyProc = newProc(
      name = verifyProcName,
      body = verifyBody,
    )
    verifyProc.addPragma(ident("exportc"))
    # codegenDecl chooses the storage-class qualifier for the verify proc:
    #
    # - **C backend** (`nim c`): `static` gives the function internal
    #   linkage (file scope, no symbol exported, no linker collisions
    #   when the same dynlib block appears in multiple TUs).
    #
    # - **C++ backend** (`nim cpp`): `static` cannot appear inside a
    #   linkage specification per C++ [dcl.link]/4. Because Nim's
    #   `{.exportc.}` emits `extern "C" ...` under cpp, combining with
    #   `static` produces `extern "C" static void ...` which g++/clang++
    #   reject. `inline` is the C++ equivalent: ODR-relaxed (multiple
    #   definitions across TUs are merged) and compatible with
    #   `extern "C"`. The verify proc only contains compile-time
    #   `_Static_assert` / `static_assert`s, so no runtime overhead
    #   distinguishes the two. See #12.
    let codegenTemplate =
      when defined(cpp): "inline $# $#$#"
      else: "static $# $#$#"
    verifyProc.addPragma(newNimNode(nnkExprColonExpr).add(
      ident("codegenDecl"),
      newStrLitNode(codegenTemplate)
    ))
    nodes.add(verifyProc)
  return nodes
