name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: nimlang/nim:2.2.0
    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          nimble test -y
