name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: nimlang/nim:2.2.0
    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: nimble test -y
